import { escapeRegExp } from "./_escape-regexp.ts";

type _RegExpFlags = "d" | "g" | "i" | "m" | "s" | "u" | "v" | "y";
type _RegExpUnicodeFlag = null | "u" | "v";

/**
 * A definition for a token type for `SimpleLexer`.
 */
export type SimpleLexerTokenDefinition<T extends keyof any = keyof any> = {
    /**
     * The name of the token.
     */
    type: T;
    /**
     * The pattern used for this token.
     *
     * Specify a string for an exact match. Specify a `RegExp` for more
     * complicated patterns.
     *
     * *Note:* Keep in mind that patterns will be combined into a single
     * concatenated `RegExp` with the `uy` flags (or `iuy` if `ignoreCase`
     * option is `true`). Flags set on the patterns in the token definition
     * itself will be _ignored_.
     */
    pattern: string | RegExp;
};

/**
 * Type representing acceptable formats to define token definitions for a
 * `SimpleLexer`
 */
export type SimpleLexerDefinitions = {
    /**
     * Token definitions for this lexer. Can be specified as an array of token
     * definition objects or
     */
    tokens:
        | Record<keyof any, SimpleLexerTokenDefinition["pattern"]>
        | SimpleLexerTokenDefinition[];
    /**
     * Set this to `true` to make the lexer patterns ignore casing.
     *
     * This cannot be set on a per-token basis. If some tokens are
     * case-sensitive and some aren't, do not enable ignore and handle this
     * in the patterns themselves.
     *
     * The `"i"` flags on the `RegExp`-based tokens have no effect on the
     * `RegExp` pattern used by the lexer.
     */
    ignoreCase?: boolean;
    /**
     * Sets the Unicode flag to be used in the combined `RegExp`.
     *
     * Valid values are: `null`, `"u"`, and `"v".
     *
     * If this is left unspecified or `undefined`, it uses the same Unicode flag
     * used in the first `RegExp`-based token pattern specifed in `tokens`
     * property. If none of the token patterns are declared in `RegExp` form,
     * the flag defaults to `"v"`.
     */
    unicodeFlag?: _RegExpUnicodeFlag;
};

/**
 * A token generated by `SimpleLexer`.
 */
export type SimpleLexerToken<T extends keyof any> = {
    /**
     * The token type identifier.
     */
    type: T;

    /**
     * The `image` is the text value of this token.
     */
    image: string;

    /**
     * The starting offset, relative to index 0 of the input text.
     */
    startOffset: number;
    /**
     * The offset the _next_ token should start with, relative to index 0 of the
     * input text.
     */
    nextOffset: number;
};

function _cloneTokenDefinition<T extends keyof any>(
    { type, pattern }: SimpleLexerTokenDefinition<T>,
) {
    return { type, pattern };
}

type _ExtractType<D extends SimpleLexerDefinitions["tokens"]> = D extends
    readonly any[] ? D[number]["type"]
    : keyof D;

function _isRegExp(input: unknown): input is RegExp {
    return input instanceof RegExp;
}

function _getRegExpUnicodeFlag(pattern: RegExp): _RegExpUnicodeFlag {
    if (pattern.unicode) {
        return "u";
    }

    if (pattern.unicodeSets) {
        return "v";
    }

    return null;
}

type _LogFunction = (message: string) => void;

/**
 * Determines the Unicode flag from a iterable list of `RegExp` patterns.
 *
 * This function also checks for consistency, and produces a warning if the
 * flags are inconsistent.
 *
 * @returns the Unicode flag used for the first `RegExp` pattern in the list, or
 *          `"v"` if the list is empty.
 */
function _getAutoRegExpUnicodeFlag(
    patterns: Iterable<RegExp>,
    logWarning: _LogFunction = console.warn,
): _RegExpUnicodeFlag {
    let unicodeFlag: _RegExpUnicodeFlag | undefined;

    for (const pattern of patterns) {
        if (unicodeFlag === undefined) {
            unicodeFlag = _getRegExpUnicodeFlag(pattern);
        } else if (unicodeFlag !== _getRegExpUnicodeFlag(pattern)) {
            logWarning("Inconsistent lexer Unicode flags");
        }
    }

    return unicodeFlag === undefined ? "v" : unicodeFlag;
}

function _getRegExpFlags(d: SimpleLexerDefinitions) {
    const flags: _RegExpFlags[] = ["y"];

    if (d.ignoreCase) {
        flags.push("i");
    }

    const patterns: RegExp[] = Object.values(d.tokens).filter(_isRegExp);

    const autoUnicodeFlag = _getAutoRegExpUnicodeFlag(patterns);

    switch (d.unicodeFlag) {
        case null:
            // No flags added.
            break;
        case "u":
        case "v":
            flags.push(d.unicodeFlag);
            break;
        default:
        case undefined:
            if (autoUnicodeFlag !== null) {
                flags.push(autoUnicodeFlag);
            }
            break;
    }

    return flags.join("");
}

/**
 * A very basic lexer that simply just takes string and `RegExp` patterns and
 * spits out the associated tokens with no advanced bells and whistles.
 *
 * @example
 *
 * ```typescript
 * const lexer = new SimpleLexer({
 *     tokens: {
 *         inlineWhitespace: /[ \t]+/u,
 *         lineEnding: /\r\n?|[\n\f\v\u2028\u2029]/u,
 *         word: /[^ \t\r\n\f\v\u2028\u2029]+/u,
 *     }
 * });
 *
 * const tokens = lexer.tokenize(input);
 *
 * for (const token of tokens) {
 *     // ...
 * }
 * ```
 */
export class SimpleLexer<const D extends SimpleLexerDefinitions> {
    #definitions: SimpleLexerTokenDefinition[];
    #matchPattern: RegExp;

    constructor(definition: D) {
        if (Array.isArray(definition.tokens)) {
            this.#definitions = definition.tokens.map(_cloneTokenDefinition);
        } else {
            this.#definitions = Object.entries(definition.tokens).map(
                ([type, pattern]) => {
                    return { type, pattern };
                },
            );
        }

        this.#matchPattern = new RegExp(
            this.#definitions
                .map((definition) => {
                    let source: string;

                    if (typeof definition.pattern === "string") {
                        source = escapeRegExp(definition.pattern);
                    } else {
                        source = definition.pattern.source;
                    }

                    return `(${source})`;
                })
                .join("|"),
            _getRegExpFlags(definition),
        );
    }

    /**
     * Returns the associated token definition for the given `RegExp` match
     * index.
     */
    #getTokenDefinitionForIndex(matchIndex: number) {
        return this.#definitions[matchIndex - 1];
    }

    #matchAt(input: string, offset: number) {
        this.#matchPattern.lastIndex = offset;
        return this.#matchPattern.exec(input);
    }

    /**
     * Returns the index of the first matched capture group.
     */
    #getFirstValidMatchIndex(matches: RegExpExecArray) {
        // First match is the full match, which we don't use. We start at
        // index 1 instead.
        for (let i = 1; i < matches.length; ++i) {
            if (matches[i] !== undefined) {
                return i;
            }
        }

        return 0;
    }

    /**
     * Matches a token at the given `offset` in `input`.
     */
    match(
        input: string,
        offset: number,
    ): SimpleLexerToken<_ExtractType<D["tokens"]>> | null {
        const matches = this.#matchAt(input, offset);

        if (matches) {
            const matchIndex = this.#getFirstValidMatchIndex(matches);

            if (matchIndex > 0) {
                const match = matches[matchIndex];
                const tokenDefinition = this.#getTokenDefinitionForIndex(
                    matchIndex,
                );

                const nextOffset = offset + match.length;

                return {
                    type: tokenDefinition.type as _ExtractType<D["tokens"]>,

                    image: match,

                    startOffset: offset,
                    nextOffset: nextOffset,
                };
            }
        }

        return null;
    }

    /**
     * Tokenizes the `input` starting at the given `offset`.
     *
     * @param input The input string.
     * @param offset The offset to start parsing the input string. Default: `0`
     */
    *tokenize(
        input: string,
        offset = 0,
    ): Generator<SimpleLexerToken<_ExtractType<D["tokens"]>>, void> {
        while (offset < input.length) {
            const token = this.match(input, offset);

            if (!token) {
                throw Error(
                    `Failed to tokenize input string at offset: ${offset}`,
                );
            }

            yield token;

            offset = token.nextOffset;
        }
    }

    /**
     * Returns a copy of the internal match pattern.
     */
    matchPattern(): RegExp {
        return new RegExp(this.#matchPattern);
    }
}
